#!/bin/bash

printf "\nsudo apt update\n"
apt update

printf "\napt list --upgradable\n"
apt list --upgradable

# get user input
COLOR="\033[1;35m"
NOCOLOR="\033[0m"
printf "\n${COLOR}Upgrade all? [Y/n]: ${NOCOLOR}"
read NPT

# upgrade and autoremove if input is blank, Y or y
if [[ -z $NPT ]] || [[ ${NPT,,} = "y" ]]
then
	printf "\nsudo apt upgrade -y\n"
	apt upgrade -y

	printf "\nsudo apt autoremove -y\n"
	apt autoremove -y
fi
